# Docker version 20.10.21, build baeda1f
# docker-compose version 1.27.4, build 40524192

version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tmp/mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  blockchain:
    build: .
    container_name: blockchain
    command: bundle exec rackup --host 0.0.0.0 -p 4000
    ports:
      - "3001:4000"
    depends_on:
      - mongodb
    environment:
      - ENVIRONMENT=production
      - NODE=4000
    volumes:
      - .:/blockchain
