development:
  clients:
    default:
      database: bud_blockchain_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: bud_blockchain_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      database: bud_blockchain_production
      hosts:
        - mongodb:27017
      options:
        server_selection_timeout: 1